## Tool to validate SoilVs vs. SoilType in Geohazard database
## Currently works for US, can easily be extended to other countries
## Developed by Srinivas Thupakula
## Developed on 6/20/2016
## Added tests by Ching-Yee Chang
# 

cat("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
#cat("\014")



packs <- c("RODBC", "data.table","gplots", "rjson", "knitr")
for (i in 1:length(packs)){
  if (!(packs[i] %in% installed.packages())) {
    install.packages(packs[i], repos='http://cran.us.r-project.org')
  }
  library(packs[i], character.only=TRUE)
}


cat("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
#cat("\014")


configdir = getwd()
source("modules/RmsJSON.r")
line = readJSON(configdir,"config.json")    
CF<-fromJSON(paste(line, collapse=""))     ## need rjson package


if(CF$GeoHazard$db != ""){
  cat("Connecting to GeoHazard DB provided by config.json  \n")
  
  db <- CF$GeoHazard$db
  ser <- CF$GeoHazard$server
  uid <- CF$GeoHazard$userid
  pwd <- CF$GeoHazard$password
  
} else {
  cat("Connecting to GeoHazard DB provided by batch file \n")
  
  userArgs <- commandArgs(trailingOnly = TRUE)
  db <- userArgs[1]
  ser <- userArgs[2]
  uid <- userArgs[3]
  pwd <- userArgs[4]
  
}




options(warn = -1)  ## suppress any warnings
ghc <- odbcDriverConnect(paste0("driver={SQL Server};
                                server=",ser,";
                                database=",db,";
                                ;uid=",uid,";pwd=",pwd))


if(ghc == -1){
  cat("\n\n\n")
  cat("ODBC connection to GeoHazard DB failed \n")
  cat("\t Please check GeoHazard DB info in config/batch file  \n")
  cat("Stopping the script \n")
  cat("\n\n")
  
  stop("Stopping the script because incorrect GeoHazard DB info \n")
  
}



t00 = Sys.time()

cat("Creating log file \n")
tStamp <- as.character(format(Sys.time(), "%Y%m%d_%Hh%Mm"))
#reportCon <- file(paste0("log/",tStamp, "_Report_", db ,".txt"),open="a")

################################################################################################
#####  Writing GeoHaz DB info to report   ######################################################
################################################################################################
# cat(paste0("GeoHazard Data Validation Report", " \n"))
# cat(paste0(" \t Report Generated by Ching-Yee Chang, cchang@rms.com", " \n"))
# cat(paste0("============================================================", "\n"))
# cat(paste0("GeoHazard DB version: ", db, " ( ", ser ," ) \n"))
# #cat(paste0(" GeoHazard DB from ", ser, " \n"))

cat(paste0("\n\n\n"))



perils = c('eq')

for(prl in perils){
  
  if(prl == 'eq'){  models = CF$EQ_Models
  } else if(prl == 'hu') {  models = c('NAHU') }
  
  for(mdl in models) {
    
#     cat(paste0("###################################################################################", "\n"))
#     cat(paste0("###################################################################################", "\n"))
#     cat(paste0("===================================================================================", "\n"))
#     cat(paste0("   ", "Peril: ", prl,  ";  Model: ", mdl  ,"\n"))
#     cat(paste0("===================================================================================", "\n"))
   
    #cat(paste0("  ", "\n"))
    
    ################################################################################################
    #####  Tests for General view   ################################################################
    ################################################################################################
    #source("modules/1_General_Test.R")    ## This has to be run
    
    
    ################################################################################################
    #####  Tests for VRG tables   ##################################################################
    ################################################################################################
    #source("modules/2_VRG_Tables_Test.R")
    
    
    
    ################################################################################################
    #####  Tests for non-VRG tables   ##############################################################
    ################################################################################################
    #source("modules/3_NonVRG_Tables_Test.R")
    
    
    ################################################################################################
    #####  Cross check between GeoHazard DB and Vuln.vgeo     ######################################
    ################################################################################################
    ## Please provide Vulnerability DB in the config file for this test
    
    #source("modules/4_GeoHaz_vs_VulnVgeo_Test.R")
    
    
    ################################################################################################
    #####  Column Ranges Tests     ######################################
    ################################################################################################
    #source("modules/6_ColumnsRanges_Test.R")
    
    #knit2html("Main.Rmd", paste0("log/Report_",tStamp,".html" ) , stylesheet = "support/css/Markdown5.css")
    #knit2html("Main.Rmd", paste0("log/Report_",tStamp,".html" ) )
    knit2html("Main.Rmd",  paste0("log/Main_", mdl, ".html"))
    
    source('modules/TableofContent.r')
                         
  }
  

}




##=================================================================================
##=================================================================================
print(Sys.time() - t00)

odbcClose(ghc)



cat("\n")
cat("\n")
cat("\014")
cat("\n")
cat("Completed Geohazard test \n \n \n")





